#!/data/data/com.termux/files/usr/bin/bash
# FB AUTO BOT
# by K90 Hack Game Mobile

black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
cyan='\033[1;36m'
white='\033[1;37m'


echo -e $blue"   _______    ___               __  ";
echo -e $blue"  / __/ _ )  / _ \___ ___ _____/ /_ ";
echo -e $blue" / _// _ |  / , _/ -_) _  / __/ __/ ";
echo -e $blue"/_/ /____/ /_/|_|\__/\_,_/\__/\__/ ";
echo -e $red"              UPLOAD BY K90 HACK GAME MOBILE ";
echo -e $green" Cảm ơn đặc biệt đến: ";
echo -e $green" https://github.com/tomiashari/fb-autoreaction";
echo -e $green" https://github.com/dfmcvn/getFBtoken ";
echo -e $green" https://github.com/tro1d/bot-reaction-gettoken";
echo -e $white"\n";
sleep 1
echo "1 ) Gõ số 1 nếu bạn chưa cài đặt php";
echo "2 ) Gõ số 2 nếu bạn đã cài đặt php";
echo "99) Gõ số 99 để thoát";
read -p "[K90 HGM] >"  act;

if [ $act = 1 ] || [ $act = 1 ]
then
apt update -y && apt upgrade -y
pkg install -y php
clear
sleep 1
php 1.php
clear
php 2.php
sleep 2
clear
php 3.php
fi

if [ $act = 2 ] || [ $act = 2 ]
then
apt update -y && apt upgrade -y
clear
php 1.php
clear
php 2.php
sleep 2
clear
php 3.php
fi

if [ $act = 99 ] || [ $act = 99 ]
then
echo -e $red'K90 HGM'
sleep 1
echo -e $red'K90 HGM'
sleep 2
echo -e $red'K90 HGM'
sleep 1
echo -e $red'(╥_╥)'
sleep 1
echo -e $red'UPLOAD BY K90 HGM'
echo -e $cyan'Luôn học hỏi người đi trước.. '
echo -e $cyan'www.facebook.com/profile.php?id=100006002596531'
sleep 2
exit
fi
